### ISSUE TITLE
Rails 5 warning

### ISSUE THREAD

**Issue by mfazekas** [jasonfb/nondestructive_migrations#13]
```Expected string default value for '--orm'; got false (boolean)```

This seems to be coming from thor.

I assume:
https://github.com/jasonfb/nondestructive_migrations/blob/master/lib/generators/data_migration_install_generator.rb#L12

should be 
```ruby
class_option :orm, type: 'boolean'
```

**Comment by jondkinney** [comment]
I'm seeing this, too. Thoughts on the fix @jasonfb? Thanks!!

**Comment by jasonfb** [comment]
sorry I'm very behind. The app I work with has not yet been upgraded to Rails 5. This gem should not be considered ready for Rails 5. I will likely get a chance to take a look this weekend if you'd like; in the meantime I'd be happy to entertain pull requests to make this gem compatible with Rails 5 and 5.1

**Comment by mfazekas** [comment]
@jasonfb PR#14 should address this warning

**Comment by jasonfb** [comment]
this is still on my to do list for Sunday (tomorrow) -- should get a chance to look at this and bring these up to Rails 5
