### ISSUE TITLE
Generate spec templates for the data migration

### ISSUE THREAD

**Issue by dimroc** [jasonfb/nondestructive_migrations#5]
It is extremely useful to have specs alongside the data migration for testing purposes. I know this doesn't exist with standard schema migrations but one can definitely test data changes better than the presence of a new column.

We do so here:
https://github.com/dimroc/datafix

**Comment by jasonfb** [comment]
This is interesting, but I typically don't run any specs against Production data, and I almost never run data migrations against test data -- so I'm not sure how this would work. 

Looks like https://github.com/dimroc/datafix does something very similar to this gem?

**Comment by dimroc** [comment]
Yes they're almost identical, but dimroc/datafix built off of a data fix
gem that didn't reuse much of ActiveRecord Migrations, which is what yours
does. That's a great thing.

I'm a big fan of writing specs for data migrations. You would write a spec
that would generate test data similar to what you would have in production,
and then get your test green to give you more confidence in the migration.
Sometimes the data migrations can get hairy and it's a great way to have
confidence in your data migration before running against production
critical data.

Here is a gist that shows a simple example:

https://gist.github.com/dimroc/3a8bec16993f384c6398

I'm sure you can imagine a migration against production data that could get
much more complicated. A test makes you feel that much safer.

**Comment by habitullence** [comment]
+1

**Comment by jasonfb** [comment]
So basically, this is a feature request so that whenever you run ```rails generate data_migration XYZ``` it also generates a match spec?
