### ISSUE TITLE
Way to turn off transactions

### ISSUE THREAD

**Issue by sgringwe** [jasonfb/nondestructive_migrations#7]
I have a long running data migration (deleting a lot of stuff) that does not need to be run in a transaction/should not as it can be long running and don't want to block the database. How can I turn it off?

**Comment by sgringwe** [comment]
It looks like ```disable_ddl_transaction!``` would work, like normal migrations. Maybe worth adding to documentation? Or even defaulting to that?

**Comment by jasonfb** [comment]
Thanks I will put that into the README

**Comment by sgringwe** [comment]
If interested, I could do a PR: https://github.com/strydercorp/nondestructive_migrations

**Comment by jasonfb** [comment]
I got it, I gotta revise the README for 1.1 anyway. thanks though
